// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include <fstream>
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1
TEST_CASE("Ex1 ", "[example]")
{
	int numbers[N] = {10, 15, 0, -25, 19, 20, 25, 30, 45, 20};
	int retval;

	retval = getDiff(numbers, N);

	REQUIRE(retval == 3);
}
TEST_CASE("Ex2 ", "[example]")
{
	int numbers[N] = {10, 20, 30, 40, 5000, 5001, 5002, 5004, 5005, 5006};
	int retval;

	retval = getDiff(numbers, N);

	REQUIRE(retval == 3);
}